### ISSUE TITLE
datasim does not validate alignments

### ISSUE THREAD

**Issue by jgedne** [yetanalytics/datasim#53] opened 2021-02-09 16:30 UTC
I am unable to get the cli to validate my alignments file. I am following the rubric in the md file.

the file is as follows: 

----------------------------
[{
  "id":"mbox::mailto:bob@example.org",
  "type": "Agent",
  "alignments":[
  	{
	"component":"https://w3id.org/xapi/scorm#initialization",
	"weight": -0.3
	},
	{
	"component":"https://w3id.org/xapi/scorm#termination",
	"weight": 0.6
	}
	]
},
{
  "id":"mbox::mailto:phil@example.org",
  "type": "Agent",
  "alignments":[
  	{
	"component":"https://w3id.org/xapi/scorm#initialization",
	"weight": -0.3
	},
	{
	"component":"https://w3id.org/xapi/scorm#termination",
	"weight": 0.6
	}
	]
},
{
  "id":"mbox::mailto:sally@example.org",
  "type": "Agent",
  "alignments":[
  	{
	"component":"https://w3id.org/xapi/scorm#initialization",
	"weight": -0.3
	},
	{
	"component":"https://w3id.org/xapi/scorm#termination",
	"weight": 0.6
	}
	]
},
{
  "id":"mbox::mailto:steve@example.org",
  "type": "Agent",
  "alignments":[
  	{
	"component":"https://w3id.org/xapi/scorm#initialization",
	"weight": -0.3
	},
	{
	"component":"https://w3id.org/xapi/scorm#termination",
	"weight": 0.6
	}
	]
},
{
  "id":"mbox::mailto:fred@example.org",
  "type": "Agent",
  "alignments":[
  	{
	"component":"https://w3id.org/xapi/scorm#initialization",
	"weight": -0.3
	},
	{
	"component":"https://w3id.org/xapi/scorm#termination",
	"weight": 0.6
	}
	]
},
{
  "id":"mbox::mailto:alice@example.org",
  "type": "Agent",
  "alignments":[
  	{
	"component":"https://w3id.org/xapi/scorm#initialization",
	"weight": -0.3
	},
	{
	"component":"https://w3id.org/xapi/scorm#termination",
	"weight": 0.6
	}
	]
}]

---------------------------

Where can I find the requirements for validating the alignments?

**Comment by cliffcaseyyet** [comment] 2021-03-19 18:19
Hi Jeff,

Could you clarify what you are trying to do? On the CLI the validate-input should have feedback if there is an issue. Are you receiving an error with that alignment?

Thanks,
Cliff

**Comment by jgedne** [comment] 2021-03-25 16:24
Yes. I was, when using the file as supplied. 

That file was resulting in an unspecified error talking about "mapping" pointing at the end of the alignments file.
I could only assume that this meant that there was some required element in the xml that was missing. 

Lacking any reference information on what the Alignment file values mean and what the possible and expected values are, I punted this issue to this forum. 

Mainly what I am looking for is the kind of deep specifications of the type that are available for the Profile Files, but for Alignments and Actors. Those filesets seem to have rather sparse documentation, unless I am just looking in the wrong places.  

thanks.

**Comment by catmeme** [comment] 2022-05-27 13:28
I ran into a similar issue, are these alignments no longer valid?

```
 docker run --rm -it -v "$(pwd)"/dev-resources:/dev-resources -i yetanalytics/datasim:latest \
           --actor-personae /dev-resources/personae/tccc_dev.json \
           --alignments /dev-resources/alignments/tccc_dev.json \
           --parameters /dev-resources/parameters/tccc_dev.json \
           --profile /dev-resources/profiles/tccc/cuf_hc_video_and_asm_student_survey_profile.jsonld \
           validate-input
```

outputs:

```
Exception in thread "main" java.io.IOException: Stream closed
        at java.base/java.io.BufferedReader.ensureOpen(BufferedReader.java:122)
        at java.base/java.io.BufferedReader.read(BufferedReader.java:279)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._loadMore(ReaderBasedJsonParser.java:276)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._parseName2(ReaderBasedJsonParser.java:1797)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._parseName(ReaderBasedJsonParser.java:1782)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:734)
        at cheshire.parse$parse_STAR_.invokeStatic(parse.clj:65)
        at cheshire.parse$parse_STAR_.invoke(parse.clj:63)
        at cheshire.parse$parse_STAR_.invokeStatic(parse.clj:66)
        at cheshire.parse$parse_STAR_.invoke(parse.clj:63)
        at cheshire.parse$parse_STAR_.invokeStatic(parse.clj:65)
        at cheshire.parse$parse_STAR_.invoke(parse.clj:63)
        at cheshire.parse$lazily_parse_array$fn__17316.invoke(parse.clj:54)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:51)
        at clojure.lang.RT.seq(RT.java:535)
        at clojure.core$seq__5420.invokeStatic(core.clj:139)
        at clojure.core$seq__5420.invoke(core.clj:139)
        at clojure.spec.alpha$every_impl$reify__2255.conform_STAR_(alpha.clj:1317)
        at clojure.spec.alpha$conform.invokeStatic(alpha.clj:171)
        at clojure.spec.alpha$conform.invoke(alpha.clj:167)
        at clojure.spec.alpha$dt.invokeStatic(alpha.clj:764)
        at clojure.spec.alpha$dt.invoke(alpha.clj:759)
        at clojure.spec.alpha$dt.invokeStatic(alpha.clj:760)
        at clojure.spec.alpha$dt.invoke(alpha.clj:759)
        at clojure.spec.alpha$pvalid_QMARK_.invokeStatic(alpha.clj:786)
        at clojure.spec.alpha$pvalid_QMARK_.invoke(alpha.clj:781)
        at clojure.spec.alpha$map_spec_impl$reify__1998$fn__2033.invoke(alpha.clj:877)
        at clojure.core$map$fn__5885.invoke(core.clj:2757)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:51)
        at clojure.lang.Cons.next(Cons.java:39)
        at clojure.lang.RT.boundedLength(RT.java:1793)
        at clojure.lang.RestFn.applyTo(RestFn.java:130)
        at clojure.core$apply.invokeStatic(core.clj:669)
        at clojure.core$apply.invoke(core.clj:662)
        at clojure.spec.alpha$map_spec_impl$reify__1998.explain_STAR_(alpha.clj:867)
        at clojure.spec.alpha$explain_data_STAR_.invokeStatic(alpha.clj:219)
        at clojure.spec.alpha$explain_data_STAR_.invoke(alpha.clj:218)
        at clojure.spec.alpha$explain_data.invokeStatic(alpha.clj:232)
        at clojure.spec.alpha$explain_data.invoke(alpha.clj:225)
        at com.yetanalytics.datasim.input$validate_alignments.invokeStatic(input.clj:61)
        at com.yetanalytics.datasim.input$validate_alignments.invoke(input.clj:59)
        at com.yetanalytics.datasim.input.Input.validate(input.clj:166)
        at com.yetanalytics.datasim.input$validate.invokeStatic(input.clj:218)
        at com.yetanalytics.datasim.input$validate.invoke(input.clj:214)
        at com.yetanalytics.datasim.main$_main.invokeStatic(main.clj:155)
        at com.yetanalytics.datasim.main$_main.doInvoke(main.clj:118)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at com.yetanalytics.datasim.main.main(Unknown Source)
```

**Comment by milt** [comment] 2022-06-03 20:04
One issue cropping up here is a bug which introduces unintended laziness in our JSON parsing code. This is responsible for the `Stream Closed`. Currently working on a fix on https://github.com/yetanalytics/datasim/pull/74

**Comment by milt** [comment] 2022-06-03 20:43
#74 should indeed fix the parse error but as I guessed there appear to be further validation issues on that profile:

```
clojure -M:cli:run --actor-personae dev-resources/personae/tccc_dev.json \
	--alignments dev-resources/alignments/tccc_dev.json \
	--parameters dev-resources/parameters/tccc_dev.json \
	--profile dev-resources/profiles/tccc/cuf_hc_video_and_asm_student_survey_profile.jsonld  \
	validate-input
Execution error (ExceptionInfo) at expound.alpha/printer-str (alpha.cljc:1006).
Unknown data:
```

I'll look into that more next week.

**Comment by milt** [comment] 2022-06-06 20:34
So two further things appear to be wrong here:

1. The TCCC profile included in this repo is not valid according to our current pattern validation code. I'll get in touch with the authors about resolving the issues there.
2. The error was being suppressed due to the error printer not accounting for changes in the output of DATASIM validation methods. The fix for that is in review https://github.com/yetanalytics/datasim/pull/76

**Comment by milt** [comment] 2022-06-06 21:28
I've confirmed that as of the latest version `0.1.7` alignments (including those from @jgedne) now properly validate, and all errors are printed. See https://github.com/yetanalytics/datasim/issues/77 for work on the TC3 profile.

**Closed by milt** 2022-06-06 21:28 UTC

**Comment by milt** [comment] 2022-06-17 22:34
TC3 profile is now fixed per https://github.com/yetanalytics/datasim/issues/77

**Comment by catmeme** [comment] 2022-07-08 14:33
Thank you, confirmed this works on my end.
