### ISSUE TITLE
Issues on make bundle

### ISSUE THREAD

**Issue by FlorianTolk** [yetanalytics/datasim#51] opened 2021-01-27 15:16 UTC
Moving this as it was submitted to the incorrect repository

I'm in an Azure instance, utilizing Ubuntu 16.04 LTS.
I've installed Java, Leiningen, Clojure, NodeJS and make
Building the API works with the following commands:
```
make clean
make bundle
cd target/bundle
/bin/server.sh > logfilename.txt &
```
But when I try to run sudo make clean, I run into this error:
```
ptadmin@ADL-DATASIM:~/datasim$ sudo make bundle
mkdir -p target/bundle/bin
cp -r scripts/*.sh target/bundle/bin
chmod +x target/bundle/bin
mkdir -p target/bundle
rm -f pom.xml
clojure -X:depstar uberjar :no-pom false :sync-pom true :aliases '[:cli]' :aot true :group-id com.yetanalytics :artifact-id datasim-cli :version '"0.1.0-SNAPSHOT"' :jar target/bundle/datasim_cli.jar :main-class com.yetanalytics.datasim.main
Execution error (FileNotFoundException) at java.io.FileInputStream/open0 (FileInputStream.java:-2).
-X:depstar (No such file or directory)
```
 

Full report at:
/tmp/clojure-15389642806237300545.edn
Makefile:12: recipe for target 'target/bundle/datasim_cli.jar' failed
make: *** [target/bundle/datasim_cli.jar] Error 1

We will add to this as we get more information

**Comment by cliffcaseyyet** [comment] 2021-01-28 19:18
Hi Florian,

Could you shoot me to the .edn report referenced at the bottom? It will contain a bit more of the stack and may help me get to the bottom of things. I suspect it's environmental or permission related. Also, could you let me know the versions of clj, java, and node present on the box?

Thanks,
Cliff

**Comment by FlorianTolk** [comment] 2021-01-28 19:21
Unfortunately I do not have access to the actual server, and have been doing all the debugging through Chris. I'll send you all of this data as soon as Chris is back at work!

Hopefuly it is just something as simple as installing a newer version of the java sdk

v/r
Florian

**Comment by cjbator88** [comment] 2021-02-01 19:32
Hi Cliff,

Florian and I installed NodeJS 12 on this instance. We ran a 'sudo make clean' and then a 'sudo make bundle' while inside of the root datasim dir.

We have:
NodeJS v12.20.1
openJDK  v11.0.10
clj v1.10.1
Lein v 2.9.5

We are still getting hit with the same error, here it is ->
```
ptadmin@ADL-DATASIM:~/datasim$ sudo make clean
rm -rf target
ptadmin@ADL-DATASIM:~/datasim$ sudo make bundle
mkdir -p target/bundle/bin
cp -r scripts/*.sh target/bundle/bin
chmod +x target/bundle/bin
mkdir -p target/bundle
rm -f pom.xml
clojure -X:depstar uberjar :no-pom false :sync-pom true :aliases '[:cli]' :aot true :group-id com.yetanalytics :artifact-id datasim-cli :version '"0.1.0-SNAPSHOT"' :jar target/bundle/datasim_cli.jar :main-class com.yetanalytics.datasim.main
Execution error (FileNotFoundException) at java.io.FileInputStream/open0 (FileInputStream.java:-2).
-X:depstar (No such file or directory)

Full report at:
/tmp/clojure-14277955257463224189.edn
Makefile:12: recipe for target 'target/bundle/datasim_cli.jar' failed
make: *** [target/bundle/datasim_cli.jar] Error 1
```

Here are the contents of latest .edn file that it's telling us to look at ->
```
{:clojure.main/message
 "Execution error (FileNotFoundException) at java.io.FileInputStream/open0 (FileInputStream.java:-2).\n-X:depstar (No such file or directory)\n",
 :clojure.main/triage
 {:clojure.error/class java.io.FileNotFoundException,
  :clojure.error/line -2,
  :clojure.error/cause "-X:depstar (No such file or directory)",
  :clojure.error/symbol java.io.FileInputStream/open0,
  :clojure.error/source "FileInputStream.java",
  :clojure.error/phase :execution},
 :clojure.main/trace
 {:via
  [{:type java.io.FileNotFoundException,
    :message "-X:depstar (No such file or directory)",
    :at [java.io.FileInputStream open0 "FileInputStream.java" -2]}],
  :trace
  [[java.io.FileInputStream open0 "FileInputStream.java" -2]
   [java.io.FileInputStream open "FileInputStream.java" 219]
   [java.io.FileInputStream <init> "FileInputStream.java" 157]
   [java.io.FileInputStream <init> "FileInputStream.java" 112]
   [clojure.lang.Compiler loadFile "Compiler.java" 7575]
   [clojure.main$load_script invokeStatic "main.clj" 475]
   [clojure.main$script_opt invokeStatic "main.clj" 535]
   [clojure.main$script_opt invoke "main.clj" 530]
   [clojure.main$main invokeStatic "main.clj" 664]
   [clojure.main$main doInvoke "main.clj" 616]
   [clojure.lang.RestFn applyTo "RestFn.java" 137]
   [clojure.lang.Var applyTo "Var.java" 705]
   [clojure.main main "main.java" 40]],
  :cause "-X:depstar (No such file or directory)"}}
```
Thanks,
Chris

**Comment by cliffcaseyyet** [comment] 2021-02-02 17:35
Chris and Florian,

I was able to reproduce the error, looking into the root cause now, should have something shortly.

Thanks,
Cliff

**Comment by cliffcaseyyet** [comment] 2021-02-02 18:44
Chris and Florian,

We figured this out. Terrible coincidental timing for this implementation, but last week on the 26th Clojure released a new version ([1.10.2](https://clojure.org/news/2021/01/26/clojure1-10-2)), and this actually impacted my ability to bundle as well (same error) due to how clojure was setup. Because we had set it to build on latest release it conflicted versions and threw those weird errors. We have now merged a fix to set it strictly to 1.10.2 and have updated to docs to reflect that the newer version of clojure needs to be installed. 

You can find linux install instructions for that version on [clojure.org](https://clojure.org/guides/getting_started#_installation_on_linux) but I will paste them here as well:

`curl -O https://download.clojure.org/install/linux-install-1.10.2.774.sh
chmod +x linux-install-1.10.2.774.sh
sudo ./linux-install-1.10.2.774.sh`

Apologies for the inconvenience. Let me know if that clears up the error.

Thanks,
Cliff

**Comment by cliffcaseyyet** [comment] 2021-02-02 18:53
@FlorianTolk @cjbator88 Forgot to tag you on the above^^ for notification.

-Cliff

**Comment by cjbator88** [comment] 2021-02-03 16:19
Hi Cliff, 

This resolved our issues for now, thanks for all of your help!

Thanks,
Chris

**Closed** 2021-02-03 16:44 UTC
